/*
* generated by Xtext
*/
package org.github;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FreemarkerEditorStandaloneSetup extends FreemarkerEditorStandaloneSetupGenerated{

	public static void doSetup() {
		new FreemarkerEditorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

