/*
 * generated by Xtext
 */
package org.github;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FreemarkerEditorRuntimeModule extends org.github.AbstractFreemarkerEditorRuntimeModule {

}
