/*
 * generated by Xtext
 */
package org.github.ui;


import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.codetemplates.ui.highlighting.SemanticHighlighter;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.github.ui.highlighting.FMHightlighter;
import org.github.ui.highlighting.FMSemanticHighlighter;
import org.github.ui.highlighting.FMTokenToAttributeMapper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FreemarkerEditorUiModule extends org.github.ui.AbstractFreemarkerEditorUiModule {
	public FreemarkerEditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	//these seem to be magic methods that work if they are there while not overriding shit???
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return FMHightlighter.class;
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return FMTokenToAttributeMapper.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return FMSemanticHighlighter.class;
	}
}
