/**
 * generated by Xtext
 */
package org.github.ui.contentassist;

import org.github.ui.contentassist.AbstractFreemarkerEditorProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class FreemarkerEditorProposalProvider extends AbstractFreemarkerEditorProposalProvider {
}
