/*
* generated by Xtext
*/
package org.github.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.github.services.FreemarkerEditorGrammarAccess;

public class FreemarkerEditorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FreemarkerEditorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected org.github.parser.antlr.internal.InternalFreemarkerEditorParser createParser(XtextTokenStream stream) {
		return new org.github.parser.antlr.internal.InternalFreemarkerEditorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Freemarker";
	}
	
	public FreemarkerEditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FreemarkerEditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
