/*
 * generated by Xtext
 */
package org.github.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.github.ui.internal.FreemarkerEditorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FreemarkerEditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FreemarkerEditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FreemarkerEditorActivator.getInstance().getInjector(FreemarkerEditorActivator.ORG_GITHUB_FREEMARKEREDITOR);
	}
	
}
