/*
* generated by Xtext
*/
package org.github;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FreemarkerEditorUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.github.ui.internal.FreemarkerEditorActivator.getInstance().getInjector("org.github.FreemarkerEditor");
	}
	
}
